version: "3.8"

services:
  project:
    build:
      context: .
      target: base
      dockerfile: Dockerfile.local
    image: rule-of-thumb-backend
    environment:
      - DOMAIN_FRONTEND=http://localhost:8080
      - DATABASE_HOST=127.0.0.1
      - DATABASE_USER=master
      - DATABASE_PASSWORD=master_pass
      - DATABASE_NAME=rule_of_thumb_mysql
    volumes:
      - ./:/project
    ports:
      - "8000:8000"
    restart: on-failure

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rule_of_thumb_mysql
      - MYSQL_USER=master
      - MYSQL_PASSWORD=pass
    volumes:
      - todo-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  todo-mysql-data: